## 05 NumPy

### NumPy First Steps

In [3]:
import numpy as np #Aliased import
data = np.random.randn(2, 3) # Random 2x3 array sampled from random normal dist

### NumPy Continued

In [18]:
# Array Shape
two_by_three = np.random.randn(2, 3)
print(two_by_three)
print(two_by_three.sum())
print(two_by_three.mean())
#two_by_three.astype(int)
two_by_three.sort()
two_by_three

[[-1.20655181 -0.14319753  0.99516584]
 [ 1.13668689  0.8884796  -1.09233134]]
0.5782516565361941
0.09637527608936569


array([[-1.20655181, -0.14319753,  0.99516584],
       [-1.09233134,  0.8884796 ,  1.13668689]])

<img src = "np_functions.png" width = 600>

In [48]:
dummy = np.array([[1,2,4], [3, 4,7]])
print(dummy[0]) #first row
np.transpose(dummy)

[1 2 4]


array([[1, 3],
       [2, 4],
       [4, 7]])

### NumPy timing experiments

In [20]:
# This will time operations
%%timeit

vals = []
imax = 10000
for i in range(1, imax+1):
    if i % 2 == 1:
        i *= -1
        vals.append(i)

UsageError: Line magic function `%%timeit` not found.


### File I/O